---
- name: Copy account keystore file
  copy:
    src: "{{ node_dir }}/keystore/accountKeystore"
    dest: "{{ quorum_data_dir }}/keystore/accountKeystore"
    mode: '0600'
  notify: restart quorum

- name: Extract address from keystore
  command: >
    grep -o '"address": *"[^"]*"'
    {{ quorum_data_dir }}/keystore/accountKeystore
  register: address_grep

- name: Set fact for address
  set_fact:
    node_address: "{{ address_grep.stdout | regex_findall('\"([0-9a-fA-F]+)\"') | first }}"

- name: Copy genesis.json
  copy:
    src: "genesis.json"
    dest: "{{ quorum_data_dir }}/genesis.json"
    mode: '0644'
  notify: restart quorum

- name: Copy static-nodes.json
  copy:
    src: "static-nodes.json"
    dest: "{{ quorum_data_dir }}/static-nodes.json"
    mode: '0644'
  notify: restart quorum

- name: Copy nodekey
  copy:
    src: "{{ node_dir }}/nodekey"
    dest: "{{ quorum_data_dir }}/nodekey"
    mode: '0600'
  notify: restart quorum

- name: Copy account password file
  copy:
    src: "{{ node_dir }}/keystore/accountPassword"
    dest: "{{ quorum_data_dir }}/keystore/password"
    mode: '0600'
  notify: restart quorum
