all:
  hosts:
    node_0:
      ansible_host: 192.241.149.57
      ansible_user: root
      node_role: validator
      node_dir: "node_0"

    node_1:
      ansible_host: 167.71.17.40
      ansible_user: root
      node_role: validator
      node_dir: "node_1"

    node_2:
      ansible_host: 167.71.27.242
      ansible_user: root
      node_role: validator
      node_dir: "node_2"

    node_3:
      ansible_host: 162.243.173.40
      ansible_user: root
      node_role: validator
      node_dir: "node_3"
